name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: check-repos
      uses: actions/checkout@v3
    - name: Set Date
      run: export MYTAG=$(date +%s)
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag slyplayer8990/cloud-v:$MYTAG
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Container to Registry
      run: docker push slyplayer8990/cloud-v:$MYTAG
