version: '3.1'
services:
  sql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: cloudy123
      MYSQL_DATABASE: cloudy
      MYSQL_USER: cloudy
      MYSQL_PASSWORD: cloudy123
    ports:
      - "3306:3306"
  php:
    image: cloudy-php
    ports:
      - "9000:9000"
    volumes:
      - ./page:/var/www/html
    restart: always
  cloudy-web:
    image: cloudy-web
    ports:
      - "8080:80"
    volumes:
      - ./page:/var/www/html
    restart: always